Name:           ros-indigo-turtlebot-rapps
Version:        2.3.2
Release:        0%{?dist}
Summary:        ROS turtlebot_rapps package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/turtlebot_rapps
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-compressed-image-transport
Requires:       ros-indigo-kobuki-auto-docking
Requires:       ros-indigo-robot-pose-publisher
Requires:       ros-indigo-tf
Requires:       ros-indigo-topic-tools
Requires:       ros-indigo-turtlebot-bringup
Requires:       ros-indigo-turtlebot-follower
Requires:       ros-indigo-turtlebot-navigation
Requires:       ros-indigo-turtlebot-panorama
Requires:       ros-indigo-turtlebot-teleop
Requires:       ros-indigo-warehouse-ros
BuildRequires:  ros-indigo-catkin

%description
The core set of turtlebot 'app manager' apps are defined in this package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Jan 21 2015 Daniel Stonier <stonier@rnd.yujinrobot.com> - 2.3.2-0
- Autogenerated by Bloom

* Tue Dec 30 2014 Daniel Stonier <stonier@rnd.yujinrobot.com> - 2.3.1-0
- Autogenerated by Bloom

